export const CONDITION_OPTIONS = [
  { key: 'posts_gte_1',        label: 'Posts publicados ≥ 1' },
  { key: 'posts_gte_10',       label: 'Posts publicados ≥ 10' },
  { key: 'posts_gte_50',       label: 'Posts publicados ≥ 50' },
  { key: 'posts_gte_100',      label: 'Posts publicados ≥ 100' },
  { key: 'posts_gte_500',      label: 'Posts publicados ≥ 500' },
  { key: 'characters_gte_1',   label: 'Personajes creados ≥ 1' },
  { key: 'characters_gte_3',   label: 'Personajes creados ≥ 3' },
  { key: 'characters_gte_10',  label: 'Personajes creados ≥ 10' },
  { key: 'rooms_gte_1',        label: 'Salas creadas ≥ 1' },
  { key: 'rooms_gte_3',        label: 'Salas creadas ≥ 3' },
  { key: 'rooms_gte_10',       label: 'Salas creadas ≥ 10' },
  { key: 'days_gte_30',        label: 'Días en la plataforma ≥ 30' },
  { key: 'days_gte_365',       label: 'Días en la plataforma ≥ 365' },
  { key: 'points_gte_100',     label: 'Puntos totales ≥ 100' },
  { key: 'points_gte_1000',    label: 'Puntos totales ≥ 1000' },
]